### ISSUE TITLE
Not get IP address

### ISSUE THREAD

**Issue by xuchunyang** [examplecode/gfw_dns_resolver#2]
This is **not** real IP address

``` sh
➜  /tmp  gcc gfw_dns_resolver.c 
➜  /tmp  ./a.out gmail.com
The real ip is: hkg03s11-in-f22.1e100.net
```

**Comment by examplecode** [comment]
Make sure you are not connected VPN?

**Comment by xuchunyang** [comment]
Yes, I'm using VPN to access the Internet but I didn't see any tips indicated that it doesn't work under a VPN :smile:
